POST http://localhost:4001/execute
Content-Type: application/json

{
  "code": "#include <stdio.h>\n#include <stdlib.h>\n\nint main(int argc, char *argv[]) {\n    if (argc != 3) {\n        printf(\"Usage: %s <num1> <num2>\\n\", argv[0]);\n        return 1;\n    }\n\n    int num1 = atoi(argv[1]);\n    int num2 = atoi(argv[2]);\n\n    int sum = num1 + num2;\n    printf(\"Sum of %d and %d is: %d\\n\", num1, num2, sum);\n\n    return 0;\n}",
  "args": ["5", "7"]
}


